### ISSUE TITLE
Error while trying to install with docker-compose.yaml

### ISSUE THREAD

**Issue by mcanyucel** [inoda/journal#64]
Thanks for this app!

I saw it while searching for a self-hosted journal/diary app. It looks really nice and I want to give it a try but I get the following error when I try to create a stack with the given docker-compose.yaml:

```
failed to deploy a stack: journal Pulling journal Warning failed to solve: process "/bin/sh -c gem update --system" did not complete successfully: exit code: 1 
```

I am not very proficient in docker or docker compose; I have searched the net but I think I am the first one encountering this error ':)

My compose file is as follows:

```
networks:
  journal:
    internal: true
  proxy:

services:
  journal:
    build: https://github.com/inoda/journal.git#main
    image: gh-inoda-journal
    volumes:
      - /home/<user>/containers/journal/data:/app:rw
    environment:
      - RAILS_ENV=production
      - SITE_DOMAIN=diary.mydomain.com
      - DATABASE_URL=postgres://replaceme:RePLAcEpAsS@journal-db/placeholder
      - CIPHER_KEY=<some key>= # openssl rand -base64 32
      - SHARING_TOKEN_CIPHER_IV=<some vector>== # openssl rand -base64 16
      - SECRET_KEY_BASE=<some string> # random alphanumerical
    ports:
      - <a  port>:3000
    networks:
      - proxy
      - journal
    restart: unless-stopped

  journal-db:
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "replaceme"]
    environment:
      - POSTGRES_DB=placeholder
      - POSTGRES_USER=replaceme
      - POSTGRES_PASSWORD=RePLAcEpAsS
    volumes:
      - /home/<user>/containers/journal/db:/var/lib/postgresql/data:rw
    networks:
      - journal
    restart: unless-stopped

```
